# Generated by Django 3.2.9 on 2021-11-24 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0003_auto_20211124_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileitem',
            name='file',
            field=models.FileField(blank=True, help_text='загружать только pdf', null=True, unique=True, upload_to='uploads/resource/file/%Y/%', verbose_name='Документы для прикрепление'),
        ),
    ]
