# Generated by Django 3.2.9 on 2021-11-24 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0005_alter_fileitem_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fileitem',
            options={'verbose_name': 'Файл pdf', 'verbose_name_plural': 'Файлы pdf'},
        ),
    ]
