# Generated by Django 3.2.9 on 2021-11-24 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование альбома')),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=100, verbose_name='Год')),
            ],
            options={
                'verbose_name': 'Год архива',
                'verbose_name_plural': 'Года архива',
            },
        ),
        migrations.CreateModel(
            name='PhotoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='Размеры фото 360*560', null=True, unique=True, upload_to='uploads/photo/', verbose_name='Галерея')),
                ('description', models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='Краткое описание фото')),
                ('photo', models.ForeignKey(help_text='Размеры фото 455*565', on_delete=django.db.models.deletion.CASCADE, related_name='photoitems', to='gallery.categoryphoto')),
            ],
            options={
                'verbose_name': 'Фотоархив',
                'verbose_name_plural': 'Фотоархивы',
            },
        ),
        migrations.AddField(
            model_name='categoryphoto',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.year', verbose_name='Год'),
        ),
    ]
