# Generated by Django 3.2.9 on 2022-03-09 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='year',
            name='image',
            field=models.ImageField(blank=True, help_text='Размеры фото 360*560', null=True, unique=True, upload_to='uploads/photo/albom/%Y/%m/%d/', verbose_name='Обложка'),
        ),
    ]
