# Generated by Django 3.2.9 on 2022-03-09 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_year_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photoitem',
            name='photo',
        ),
        migrations.DeleteModel(
            name='Albom',
        ),
        migrations.DeleteModel(
            name='PhotoItem',
        ),
        migrations.DeleteModel(
            name='Year',
        ),
    ]
