# Generated by Django 3.2.9 on 2021-11-24 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20211124_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoitem',
            name='image',
            field=models.ImageField(blank=True, help_text='Размеры фото 360*560', null=True, unique=True, upload_to='uploads/photo/albom/%Y/%m/%d/', verbose_name='Галерея'),
        ),
    ]
