# Generated by Django 3.2.9 on 2022-03-09 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='albom',
            name='published',
            field=models.BooleanField(default=True, verbose_name='Опубликовать?'),
        ),
        migrations.AddField(
            model_name='year',
            name='published',
            field=models.BooleanField(default=True, verbose_name='Опубликовать?'),
        ),
    ]
