# Generated by Django 3.2.9 on 2022-03-09 05:23

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='url')),
                ('published', models.BooleanField(default=True, verbose_name='Отображать?')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='blog.category', verbose_name='Родительская категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Заголовок')),
                ('slug', models.SlugField(unique=True, verbose_name='url')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Содержание')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('edit_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата редактирования')),
                ('published_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата публикации')),
                ('image', models.ImageField(help_text='Размеры фото 636x420', upload_to='uploads/blog/%Y/%m/%d/', verbose_name='Главная фотография')),
                ('published', models.BooleanField(default=True, verbose_name='Опубликовать?')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Просмотрено')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
            },
        ),
        migrations.CreateModel(
            name='PhotoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='Размеры фото 360*560', null=True, unique=True, upload_to='uploads/blog/%Y/%m/%d/', verbose_name='Галерея')),
                ('description', models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='Краткое описание фото')),
                ('photo', models.ForeignKey(help_text='Размеры фото 455*565', on_delete=django.db.models.deletion.CASCADE, related_name='photoitems', to='blog.post')),
            ],
            options={
                'verbose_name': 'Галерея постов',
                'verbose_name_plural': 'Галерея постов',
            },
        ),
        migrations.CreateModel(
            name='FileItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, help_text='загружать только pdf', null=True, unique=True, upload_to='uploads/blog/file/%Y/%m/%d', verbose_name='Документы для прикрепление')),
                ('description', models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='Краткое описание ')),
                ('doc', models.ForeignKey(help_text='Pdf файлы', on_delete=django.db.models.deletion.CASCADE, related_name='fileitems', to='blog.post')),
            ],
            options={
                'verbose_name': 'Файл pdf',
                'verbose_name_plural': 'Файлы pdf',
            },
        ),
    ]
