# Generated by Django 3.2.9 on 2021-11-24 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoitem',
            name='image',
            field=models.ImageField(blank=True, help_text='Размеры фото 360*560', null=True, unique=True, upload_to='uploads/blog/%Y/%m/%d/', verbose_name='Галерея'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='uploads/blog/%Y/%m/%d/', verbose_name='Главная фотография'),
        ),
    ]
