# Generated by Django 3.2.9 on 2021-11-23 02:24

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20211123_0738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='service',
            name='url',
            field=models.SlugField(blank=True, max_length=100, null=True, verbose_name='Внешняя ссылка'),
        ),
    ]
