# Generated by Django 3.2.9 on 2021-11-23 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_auto_20211123_0824'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='category',
            new_name='categoryservice',
        ),
    ]
