# Generated by Django 3.2.9 on 2021-11-24 01:42

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_rename_category_service_categoryservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='filepdf',
            field=models.FileField(blank=True, null=True, upload_to='source/%Y/%m/%d/', verbose_name='Исходник pdf'),
        ),
        migrations.AlterField(
            model_name='service',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Содержание'),
        ),
    ]
