# Generated by Django 3.2.9 on 2021-11-24 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_auto_20211124_0742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='filepdf',
        ),
        migrations.CreateModel(
            name='FileItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(blank=True, help_text='загружать только pdf', null=True, unique=True, upload_to='uploads/service/file/%Y/%', verbose_name='Документы для прикрепление')),
                ('description', models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='Краткое описание ')),
                ('doc', models.ForeignKey(help_text='Pdf файлы', on_delete=django.db.models.deletion.CASCADE, related_name='fileitems', to='service.service')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлы',
            },
        ),
    ]
