# Generated by Django 3.2.9 on 2021-12-14 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20211209_0846'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='stroke',
            field=models.BooleanField(default=False, verbose_name='Меню на 1 строке'),
        ),
    ]
