# Generated by Django 3.2.9 on 2022-03-09 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='1920*714', upload_to='uploads/slide/%Y/%m/%d/', verbose_name='Главное фото для слайдера')),
                ('title', models.CharField(blank=True, max_length=150, null=True, verbose_name='Заголовок фото')),
                ('link', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ссылка на статью')),
                ('published', models.BooleanField(default=True, verbose_name='Опубликовать?')),
                ('is_active', models.BooleanField(default=False, verbose_name='Главное фото?')),
            ],
            options={
                'verbose_name': 'Слайдер',
                'verbose_name_plural': 'Слайдеры',
            },
        ),
    ]
