# Generated by Django 3.2.9 on 2021-11-24 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slide', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='link',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ссылка на статью'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='title',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Заголовок фото'),
        ),
    ]
