# Generated by Django 3.2.9 on 2021-11-24 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slide', '0002_auto_20211124_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='image',
            field=models.ImageField(help_text='1920*714', upload_to='slide/%Y/%m/%d/', verbose_name='Главное фото для слайдера'),
        ),
    ]
