# Generated by Django 3.2.9 on 2021-11-24 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slide', '0003_alter_slide_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='image',
            field=models.ImageField(help_text='1920*714', upload_to='uploads/slide/%Y/%m/%d/', verbose_name='Главное фото для слайдера'),
        ),
    ]
