# Generated by Django 3.2.9 on 2021-12-27 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slide', '0004_alter_slide_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='published',
            field=models.BooleanField(default=True, verbose_name='Опубликовать?'),
        ),
    ]
